sudo: required
dist: bionic
language: node_js
node_js:
  - '14.15'

before_install:
  - sudo apt update
  - sudo apt install software-properties-common
  - sudo apt-add-repository --yes --update ppa:ansible/ansible
  - sudo apt install ansible
  - npm install -g @angular/cli
  - npm install

script:
  - npm run build-prod
  - echo ${SSH_PRIVATE_KEY} | base64 --decode > ansible/mykey
  - chmod 600 ansible/mykey
  - pushd ansible && ansible-playbook service.yaml
  - popd && rm ansible/mykey

