- hosts: frontend_service
  gather_facts: false
  vars:
    local_ansible_path: /home/travis/build/thamaraiselvam/spring-petclinic-angular
    remote_serve_path: /var/www/html/petclinic
  tasks:
    - block:
      - name: Copy build files to serving directory
        synchronize:
          src: "{{local_ansible_path}}/dist/"
          dest: "{{remote_serve_path}}"
      - name: Restart server
        systemd:
          name: nginx
          enabled: true
          state: restarted
      become: yes
      become_user: root
