- hosts: frontend_service
  remote_user: root
  gather_facts: false
  vars_files:
    - values.yaml
  tasks:
    - block:
      - name: Copy build files to serving directory
        synchronize:
          src: "{{local_ansible_path}}/dist/"
          dest: "{{remote_serve_path}}"
      - name: Restart server
        systemd:
          name: nginx
          enabled: true
          state: restarted
      become: yes
      become_user: root
